# Travis-CI file for Espruino

language: c

# Maybe someday when travis-ci authorizes the ppa:
# https://github.com/travis-ci/apt-source-whitelist/issues/219
#sudo: false
#addon:
#  apt:
#    sources:
#      - ppa:team-gcc-arm-embedded/ppa
#    packages:
#      - libsdl1.2-dev gcc-arm-embedded

before_script:
 - source ./scripts/provision-framework.sh $BOARD

after_script:
  - ls *.bin *.hex *.tgz | xargs -I {} curl -v -F "binary=@{}" "http://www.espruino.com/travis_upload.php?commit=$TRAVIS_COMMIT"
  # upload to an S3 bucket, requires S3_BUCKET, AWS_ACCESS_KEY_ID and AWS_SECRET_KEY to be set
  # in environment using travis' repository settings
  - "if [[ -n \"$S3_BUCKET\" && -n \"$AWS_ACCESS_KEY_ID\" ]]; then
      echo Uploading *.tgz to $S3_BUCKET;
      curl -Ls https://github.com/rlmcpherson/s3gof3r/releases/download/v0.5.0/gof3r_0.5.0_linux_amd64.tar.gz | tar zxf - gof3r_0.5.0_linux_amd64/gof3r;
      mv gof3r*/gof3r .;
      ls *.tgz | xargs -I {} ./gof3r put -b $S3_BUCKET -k espruino/{} --acl public-read -p {};
      ls *.tgz | xargs -I {} echo \"URL: http://$S3_BUCKET/espruino/{}\";
      fi"

compiler:
  - gcc

env:
  global:
    - TRAVIS=1
    - V=0
    - RELEASE=1
  matrix:
    - BOARD=ESP32
    - BOARD=ESP8266_BOARD
    - BOARD=ESPRUINOBOARD
    - BOARD=PICO
    - BOARD=MICROBIT
    - BOARD=NRF52832DK
    - BOARD=OLIMEXINO_STM32
    - BOARD=MAPLERET6_STM32
    - BOARD=HYSTM32_24
    - BOARD=HYSTM32_28
    - BOARD=HYSTM32_32
    - BOARD=STM32VLDISCOVERY
    - BOARD=STM32F3DISCOVERY
    - BOARD=STM32F4DISCOVERY
    - BOARD=NUCLEOF401RE
    - BOARD=NUCLEOF411RE
    - BOARD=LINUX
    - BOARD=EFM32GGSTK
    - BOARD=NUCLEOL476RG

script: make

notifications:
  email: false
